"""OpenRange core public API."""

from openrange.core.admit import (
    AdmissionFailure,
    BuildEvent,
    Snapshot,
    admit,
    snapshot_to_dict,
    validate_task_bindings,
)
from openrange.core.curriculum import (
    CurriculumPolicy,
    Direction,
    auto_evolve,
    direction_from_reports,
)
from openrange.core.errors import (
    AdmissionError,
    EpisodeRuntimeError,
    ManifestError,
    OpenRangeError,
    PackError,
    StoreError,
)
from openrange.core.pack import (
    PACKS,
    Backing,
    Builder,
    BuildResult,
    EpisodeReportLike,
    EpisodeResult,
    FeasibilityVerdict,
    LLMBackendLike,
    Manifest,
    Mutation,
    Pack,
    PackPrior,
    PackRegistry,
    RuntimeHandle,
    TaskFamily,
    TaskSeed,
    TaskSpec,
)
from openrange.core.store import SnapshotStore
from openrange.core.turn import ActorTurn

__all__ = [
    "PACKS",
    "ActorTurn",
    "AdmissionError",
    "AdmissionFailure",
    "Backing",
    "BuildEvent",
    "BuildResult",
    "Builder",
    "CurriculumPolicy",
    "Direction",
    "EpisodeReportLike",
    "EpisodeResult",
    "EpisodeRuntimeError",
    "FeasibilityVerdict",
    "LLMBackendLike",
    "Manifest",
    "ManifestError",
    "Mutation",
    "OpenRangeError",
    "Pack",
    "PackError",
    "PackPrior",
    "PackRegistry",
    "RuntimeHandle",
    "Snapshot",
    "SnapshotStore",
    "StoreError",
    "TaskFamily",
    "TaskSeed",
    "TaskSpec",
    "admit",
    "auto_evolve",
    "direction_from_reports",
    "snapshot_to_dict",
    "validate_task_bindings",
]
